import Head from "next/head";
import dynamic from 'next/dynamic'
import React from 'react'
import { Canvas } from '@react-three/fiber'
import { Physics, Debug } from '@react-three/cannon'
import { OrbitControls, Stats } from '@react-three/drei'

import styles from "../styles/Home.module.css";
import { Scene } from '../components/Scene'

const DynamicComponentWithNoSSR = dynamic(
  () => import('../components/VHACD'),
  { ssr: false }
)

export default function Demo() {

  return (
    <>
      <title>Demo</title>
      <Contents />
    </>
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DynamicComponentWithNoSSR />

      <main className={styles.main}>
        <h1 className={styles.title}>Demo</h1>
        <Contents />
      </main>
    </div>
  );
}

const Contents = () => {
  return (
    <Canvas dpr={[1, 2]} shadows gl={{ alpha: false }} camera={{ position: [-2, 1, 7], fov: 50 }}>
      <Stats />
      <color attach="background" args={['#f6d186']} />
      <hemisphereLight intensity={1} />
      <spotLight position={[5, 5, 5]} angle={0.75} penumbra={1} intensity={1} castShadow shadow-mapSize-width={1028} shadow-mapSize-height={1028} />
      <OrbitControls />
      <Physics iterations={50} broadphase="SAP">
        {/* <Debug scale={1} color="black"> */}
          <Scene />
        {/* </Debug> */}
      </Physics>
    </Canvas>
  )
}
